# Generated by Django 3.2 on 2021-12-28 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_auto_20211228_2318'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
