# Generated by Django 3.2 on 2021-12-28 16:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0002_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_location',
            field=models.FileField(default=django.utils.timezone.now, upload_to='media/videos'),
            preserve_default=False,
        ),
    ]
