# Generated by Django 3.2 on 2021-12-28 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0003_video_video_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='slug',
            field=models.SlugField(default='f9187986-2e65-489d-966f-5e85f651d2f6'),
        ),
    ]
